name: Build and deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 1. Checkout the repo
            - name: Checkout repository
              id: checkout
              uses: actions/checkout@v5

            # 2. Set up Node.js
            - name: Setup Node.js
              id: setup-node
              uses: actions/setup-node@v5
              with:
                  node-version: 22

            # 3. Install dependencies
            - name: Install dependencies
              id: install-dependencies
              run: npm ci

            # 4. Build VitePress
            - name: Build VitePress
              id: build
              run: npm run build

            # 5. Upload static files as artifact
            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./.vitepress/dist/

    # Deployment job
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
